### ISSUE TITLE
Cannot install nushell via winget

### ISSUE THREAD

**Issue by vigneshmanick** [nushell/nushell#13281]
### Question

I am unable to install via winget. The command i used is as follows  `winget install --id Nushell.Nushell` 

The installation errors out with the following error message

```pwsh
winget install --id Nushell.Nushell
Found nu [Nushell.Nushell] Version 0.95.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\vm\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Nushell.Nushell.0.95.0-2024-07-01-19-53-19.226.log
```

Shouldn't winget install as a user installation? I am also not getting any prompts for the UAC. 

1. Is it possible to install into Appdata?
2. If not how do i get the UAC prompt

Thanks!

### Log
```log
Action start 15:49:26: InstallFinalize.
MSI (s) (B8:9C) [15:49:26:017]: Product: nu -- Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.

Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.
Action ended 15:49:26: InstallFinalize. Return value 3.
Action ended 15:49:26: INSTALL. Return value 3.
Property(S): DiskPrompt = nu Installation
Property(S): UpgradeCode = {82D756D2-19FA-4F09-B10F-64942E89F364}
Property(S): APPLICATIONFOLDER = C:\Program Files\nu\
Property(S): Bin = C:\Program Files\nu\bin\
Property(S): WindowsTerminalProfileAppFolder = C:\Users\vm\AppData\Local\Microsoft\Windows Terminal\Fragments\nu\
Property(S): WixUIRMOption = UseRM
Property(S): ALLUSERS = 1
Property(S): ARPINSTALLLOCATION = C:\Program Files\nu\
```

**Comment by fdncred** [comment]
My guess is that winget tries to install nu into c:\program files which sometimes requires permissions. We'd probably support a PR moving it to the users appdata folder.

**Comment by vigneshmanick** [comment]
thanks for the response, from the other comment i thought that the winget install also installs to the appdata.
https://github.com/nushell/nushell/issues/12748#issuecomment-2093222842

So if i were to run the MSI directly, then it's possible to install directly to the Appdata folder?

**Comment by fdncred** [comment]
You can see the most recent change here https://github.com/nushell/nushell/pull/12720 but I think it still wants to install in program files https://github.com/nushell/nushell/blob/e5cf4863e95126080439479328f55a26b9f65add/wix/main.wxs#L24-L30

**Comment by ErichDonGubler** [comment]
I had this issue yesterday with an upgrade to Nushell 0.95 on Windows 11. The [admin-elevated install context workaround from @fdncred](https://github.com/nushell/nushell/issues/13281#issuecomment-2200767326) worked for me. I think this is a regression, though, because I recall getting UAC prompts (as expected) with previous versions' installers.

**Comment by fdncred** [comment]
I feel like removing the winget-pkgs delivery altogether. All it does is cause headaches for people and no one on the core team is a winget expert. It's a big hassle to support. So, consider this a plea for help fix our winget-pkgs delivery situation. If you don't like what it's doing, please figure out a good solution to fix it. Otherwise, we'll probably just end up removing it. We don't create install packages for other operating systems.

**Comment by ErichDonGubler** [comment]
I get enough value out of `winget` distribution that I'm willing to step up and at least try to fix this issue.

My first hypothesis is that we're now installing without UAC, but maybe need UAC to uninstall the old version in `Program Files`? Will figure out how to test this.

**Comment by fdncred** [comment]
I appreciate you stepping in to help. ❤️ 

What I think needs to happen is to change the location from `Program Files` to `LOCALAPPDATA\Programs`. LocalAppData maps to `systemdrive\users\username\appdata\local`. So, this should be fully under the user's control without the need for UAC.

We may need UAC, like you say, to uninstall. I have no clue.

**Comment by dander** [comment]
I've just verified this morning that the installer is properly authored for both per-user and per-system installation (running it manually installs per-user by default). It looks like the problem is with the winget manifest:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/n/Nushell/Nushell/0.95.0/Nushell.Nushell.installer.yaml#L13-L14

Setting `ALLUSERS=1` turns on per-system install. I've been trying to figure out where that is coming from this morning, but haven't tracked it down yet.

Winget has an option `--scope user`, but [that isn't working either](https://github.com/nushell/nushell/issues/11240) (probably just overridden by the manifest property). I think winget defaults to per-user anyway.

**Comment by dander** [comment]
Looking at the other winget manifests, `0.94.1` didn't have the install flag specified, but it showed up in `0.94.2`. I don't see any package related changes between those. So maybe it was a change in the `vedantmgoyal2009/winget-releaser` github action or [Komac](https://github.com/russellbanks/komac)

**Comment by fdncred** [comment]
I noticed someone changed our winget-pkgs release last time to add ALLUSERS=1. https://github.com/microsoft/winget-pkgs/pull/157957 I'm not sure what that was all about.

**Comment by fdncred** [comment]
> I've just verified this morning that the installer is [properly authored](https://learn.microsoft.com/en-us/windows/win32/msi/installation-context) for both per-user and per-system installation (running it manually installs per-user by default). It looks like the problem is with the winget manifest: https://github.com/microsoft/winget-pkgs/blob/master/manifests/n/Nushell/Nushell/0.95.0/Nushell.Nushell.installer.yaml#L13-L14
> 
> Setting `ALLUSERS=1` turns on per-system install. I've been trying to figure out where that is coming from this morning, but haven't tracked it down yet.
> 
> Winget has an option `--scope user`, but [that isn't working either](https://github.com/nushell/nushell/issues/11240) (probably just overridden by the manifest property). I think winget defaults to per-user anyway.

I couldn't get it to install with winget so i'm not sure what the magic command line params are for it.

**Comment by dander** [comment]
winget cli option is `--scope           Select install scope (user or machine)`

I also tried the [configuration option](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#scope) with the same result. Both times I could see the installer had `ALLUSERS=1` in the log. It's definitely being overridden from the default value which is supposed to allow the mode to change depending on the user context (being logged in as an administrator with elevated privileges or not).
![image](https://github.com/nushell/nushell/assets/1302979/574f6e28-efcf-4535-886d-7e95568edfcc)

**Comment by fdncred** [comment]
At least those values in your screenshot seem to match our wix file.
https://github.com/nushell/nushell/blob/0d060aeae85ac53baf89f776bc236f7dad0ba3cf/wix/main.wxs#L60-L61

**Comment by ErichDonGubler** [comment]
I've spent a few hours looking at things, and I really want to write a report of what I've been learning about the installer. However, I don't have anything that I've been able to compress into a short time to type, so I might have to punt on re-hashing my notes until my next weekend.

Based on what I've learned about the MSI installer we produce with WiX, we have a "dual-purpose" installer that only installs to `Program Files` when you force it to (i.e., via the `ALLUSERS=1` or `ALLUSERS=2 MSIINSTALLPERUSER=""` env. var. combos). When you do force it to install to the machine context, you _have_ to be in an elevated context for the install to succeed; otherwise, we fail with error code 1603.

This is rather different than I expected; falling back to a UAC prompt seems like a better behavior than outright failing. If we can fix this, I think we can have "perfect" behavior for the MSI installer: We can make it so that, by default, `winget install --id Nushell.Nushell` installs per-user, but it could be forced to install in a machine context with `--scope machine`.

**Comment by fdncred** [comment]
Sounds like a reasonable approach. I have no idea how to accomplish that though. 😆

**Comment by ErichDonGubler** [comment]
The good news is that I've been playing with Winget package authoring (does anybody want that to be turned into contributor docs?), and I think I know how to make our package use `--scope` properly. So, I feel confident in handling that front. ☝🏻 I believe we can do this by duplicating `Installers` entries in that have variation in a `Scope` field being set to `user`, `machine` or omitted. CC @dander, who was [noting](https://github.com/microsoft/winget-pkgs/pull/157957#issuecomment-2218309924) we might want to author a package without these; I think that approach isn't workable, based on my testing of different CLI invocations.

After the above, the remaining scope is to figure out how to configure WiX (if it's possible) to request access via UAC on machine-scope installations.

I think these two changes can be uncoupled into separate action items, since we've already published a version of the installer that has the behavior we'd like to change (viz., wanting UAC). I can plan on getting `scope` variants of the Winget package squared away first, if that sounds good.

**Comment by fdncred** [comment]
Seems like stephen's 2nd option (below) is better to me.

> Another would be moving these to the installer level, and duplicating the current installers with user scope and switches - which would allow these to be selected at insatll time, and I believe default to user scope for install.

**Comment by ErichDonGubler** [comment]
Yes, that's effectively what I'm proposing. :+1:

**Comment by ErichDonGubler** [comment]
> Seems like stephen's 2nd option (below) is better to me. I think I'd like to get this working if possible.
> 
> > Another would be moving these to the installer level, and duplicating the current installers with user scope and switches - which would allow these to be selected at insatll time, and I believe default to user scope for install.

Yes, this is effecitvrly what I'm proposing. 👍🏻

**Comment by vigneshmanick** [comment]
what is required to move this issue forward? i can help with testing this locally (not well versed in packaging winget packages :) ).

**Comment by pewill** [comment]
As stated previously in this thread the package itself looks valid for using in both _per user_ and _per machine_ installation but there seem to be a few moving pieces involved in the winget manifest creation. Looking at the [Publish winget package action for 0.97.1](https://github.com/nushell/nushell/actions/runs/10483231080/job/29035596879#step:2:81) it outputs the following installer manifest using Komac (a bit abbreviated for clarity)
```yaml
PackageIdentifier: Nushell.Nushell
PackageVersion: 0.97.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: ALLUSERS=1
UpgradeBehavior: install
Commands:
- nu
ReleaseDate: 2024-08-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.97.1/nu-0.97.1-x86_64-pc-windows-msvc.msi
  InstallerSha256: FE662D37B3D4058ACF2085E68B1B40884A61EDEAE235059D6B0C7CCCF1A92FF9
  ProductCode: '{4FFEF0CC-4BE0-4DD0-ABCC-B64542E3AEA5}'
```
The ALLUSERS=1 switch will make the msi use per machine installation.
To support both per user and per machine installation via winget the manifest would need to look like this
```yaml
PackageIdentifier: Nushell.Nushell
PackageVersion: 0.97.1
InstallerLocale: en-US
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress

UpgradeBehavior: install
Commands:
- nu
ReleaseDate: 2024-08-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.97.1/nu-0.97.1-x86_64-pc-windows-msvc.msi
  InstallerSha256: FE662D37B3D4058ACF2085E68B1B40884A61EDEAE235059D6B0C7CCCF1A92FF9
  ProductCode: '{4FFEF0CC-4BE0-4DD0-ABCC-B64542E3AEA5}'
  InstallerSwitches:
    Custom: ALLUSERS=1
  Scope: machine
- Architecture: x64
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.97.1/nu-0.97.1-x86_64-pc-windows-msvc.msi
  InstallerSha256: FE662D37B3D4058ACF2085E68B1B40884A61EDEAE235059D6B0C7CCCF1A92FF9
  ProductCode: '{4FFEF0CC-4BE0-4DD0-ABCC-B64542E3AEA5}'
  Scope: user
```
That would give the following results in a non-elevated terminal
`winget install Nushell.Nushell` -> installs per user
`winget install Nushell.Nushell --scope user` -> installs per user
`winget install Nushell.Nushell --scope machine` -> fails (ideally UAC would be shown)

The behavior in an elevated terminal
`winget install Nushell.Nushell` -> installs per user
`winget install Nushell.Nushell --scope user` -> installs per user
`winget install Nushell.Nushell --scope machine` -> installs per machine

There is some logic involved in how Komac determines which scope to use based on value of ALLUSERS, the presence of _machine_ or _user_ in the InstallerUrl and the scopes used in previous version. In addition, the action for publishing to winget is `vedantmgoyal2009/winget-releaser@v2` and uses Komac 1.11.0 which is a bit older version.
That said, I'm not sure what is the best route forward but perhaps test how Komac 2 interprets the scope and potentially create an issue on how to publish a single package authored MSI for both per user and per machine use.
