### ISSUE TITLE
Does nushell table have vertical column based output?

### ISSUE THREAD

**Issue by longkai** [nushell/nushell#14257]
### Question

When dealing with many column based tables or some column value too long, the table output is hard to read and often omit tailing columns.

So is there a way to render the table as a list of records?

I know it could be done by print each row as records, but that would have no index and feel a little strange.

Just like mysql `\G` or `--auto-vertical-output` option:

```
mysql> desc reviews_by_device\G

*************************** 1. row ***************************
  Field: ar_id
   Type: int(10)
   Null: NO
    Key: PRI
Default: NULL
  Extra: auto_increment
*************************** 2. row ***************************
  Field: ar_pkg_name
   Type: varchar(50)
   Null: YES
    Key:
Default: NULL
  Extra:
*************************** 3. row ***************************
  Field: ar_ver_code
   Type: int(5)
   Null: YES
    Key:
Default: NULL
  Extra:
*************************** 4. row ***************************
...
17 rows in set (0.00 sec)
```
