### ISSUE TITLE
Right prompt overwrites the Starship config

### ISSUE THREAD

**Issue by filipdutescu** [nushell/nushell#14268]
### Describe the bug

I have a very simple setup, where I use Starship for the prompt. Normally, on my right prompt, where I have the git branch if in a git repo, the `on` text is white. In Nushell, this text is the same colour as the git branch name.

![image](https://github.com/user-attachments/assets/ecac6c4f-74da-471e-a3da-2a655760fa2a)

### How to reproduce

1. Create the following config:
```nushell
let carapace_completer = {|spans: list<string>|
    carapace $spans.0 nushell ...$spans
    | from json
    | if ($in | default [] | where value =~ '^-.*ERR$' | is-empty) { $in } else { null }
}
let external_completer = {|spans|
    let expanded_alias = scope aliases
    | where name == $spans.0
    | get -i 0.expansion

    let spans = if $expanded_alias != null {
        $spans
        | skip 1
        | prepend ($expanded_alias | split row ' ' | take 1)
    } else {
        $spans
    }

    match $spans.0 {
        _ => $carapace_completer
    } | do $in $spans
}

$env.config = {
  edit_mode: vi
  render_right_prompt_on_last_line: true
  cursor_shape: {
    vi_insert: block
    vi_normal: block
    emacs: line
  }

  show_banner: false

  completions: {
    external: {
      enable: true
      completer: $external_completer
    }
  }
}

# setup for starship
$env.STARSHIP_SHELL = "nu"
$env.PROMPT_INDICATOR = ""
$env.PROMPT_INDICATOR_VI_INSERT = ""
$env.PROMPT_INDICATOR_VI_NORMAL = ""
$env.PROMPT_MULTILINE_INDICATOR = ""

use ~/.cache/starship/init.nu
```
2. Create the following `init.nu` file for Starship (by following [their docs](https://starship.rs/guide/#step-2-set-up-your-shell-to-use-starship)):
```nushell
# this file is both a valid
# - overlay which can be loaded with `overlay use starship.nu`
# - module which can be used with `use starship.nu`
# - script which can be used with `source starship.nu`
export-env { $env.STARSHIP_SHELL = "nu"; load-env {
    STARSHIP_SESSION_KEY: (random chars -l 16)
    PROMPT_MULTILINE_INDICATOR: (
        ^/etc/profiles/per-user/myuser/bin/starship prompt --continuation
    )

    # Does not play well with default character module.
    # TODO: Also Use starship vi mode indicators?
    PROMPT_INDICATOR: ""

    PROMPT_COMMAND: {||
        # jobs are not supported
        (
            ^/etc/profiles/per-user/myuser/bin/starship prompt
                --cmd-duration $env.CMD_DURATION_MS
                $"--status=($env.LAST_EXIT_CODE)"
                --terminal-width (term size).columns
        )
    }

    config: ($env.config? | default {} | merge {
        render_right_prompt_on_last_line: true
    })

    PROMPT_COMMAND_RIGHT: {||
        (
            ^/etc/profiles/per-user/myuser/bin/starship prompt
                --right
                --cmd-duration $env.CMD_DURATION_MS
                $"--status=($env.LAST_EXIT_CODE)"
                --terminal-width (term size).columns
        )
    }
}}
```
3. Run the shell, with the following right prompt in the Starship config, in a directory that is part of a git repository:
```toml
# ...
right_format = "$git_branch$git_commit$git_state$git_metrics$git_status$docker_context"
# ...
```

### Expected behavior

I expected `nu` to not overwrite the colour of the `on` word, but keep it as is with my default shell (ZSH - see picture above).

### Configuration

Nushell info:

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.96.1                                                            |
| major              | 0                                                                 |
| minor              | 96                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (built from a source tarball) |
| cargo_version      | cargo 1.79.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  |                                                                   |

Starship info:

| key | value |
| ---- | ------- |
| starship" | 1.20.1 |
| branch: | |
| commit_hash: | |
| build_time: | 1980-01-01 00:00:00 +00:00 |
| build_env: | rustc 1.79.0 (129f3b996 2024-06-10) (built from a source tarball), |

**Comment by fdncred** [comment]
Does it do the same thing on the most recent version of nushell 0.99.1?

**Comment by filipdutescu** [comment]
yep, tried it, on both Linux and Windows and got the same result

**Comment by fdncred** [comment]
You may try and to put an `(ansi reset);` in the closure to stop the ansi bleeed. I'm not sure otherwise. I don't use starship.

**Comment by filipdutescu** [comment]
I tried that. It did not work. I also confirmed that the output of

```nu
(
    ^/etc/profiles/per-user/filip/bin/starship prompt
    --right
    --cmd-duration $env.CMD_DURATION_MS
    $"--status=($env.LAST_EXIT_CODE)"
    --terminal-width (term size).columns
)
```

outputs as expected, will the colours being fine. it seems like something about the cursor bleeds into the right prompt, as I tried with a different terminal emulator (rio) and there my cursor was the same colour as the `on` text.

**Comment by filipdutescu** [comment]
in between left prompt and right prompt, the text is also not using any of my Starship theme colours so i am starting to believe the issue is actually with Nushell's theme

**Comment by fdncred** [comment]
I'm not having issues. Maybe if you shared your starship.toml?
![image](https://github.com/user-attachments/assets/42f948d8-1b4a-4f1f-affc-22a9fde7a281)

**Comment by filipdutescu** [comment]
here it is:

```toml
add_newline = false
format = "$username$hostname$nix_shell$localip$kubernetes$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$vlang$vagrant$zig$crystal$cmd_duration$directory$character"
palette = "springan"
right_format = "$git_branch$git_commit$git_state$git_metrics$git_status$docker_context"
scan_timeout = 10

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[gcloud]
disabled = true

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[line_break]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
heuristic = true

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[palettes.springan]
black = "#1e1f21"
blue = "#7b82b9"
cyan = "#7bb0b9"
green = "#8ab97b"
light-black = "#303436"
light-blue = "#949ac7"
light-cyan = "#94bfc7"
light-green = "#a1c794"
light-purple = "#c193c8"
light-red = "#c97e80"
light-white = "#e7e5df"
light-yellow = "#d3d175"
purple = "#b17aba"
red = "#c16a6d"
white = "#d3d0cb"
yellow = "#c9c76b"

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[username]
format = "[$user]($style) "

[vagrant]
disabled = true

[vcsh]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
```
