### ISSUE TITLE
MSI installer prompts for admin permissions even though it installs to `%LOCALAPPDATA%\Programs`

### ISSUE THREAD

**Issue by o-l-a-v** [nushell/nushell#14786]
### Describe the bug

The MSI installer prompts for admin permissions even though it installs as current user / to `%LOCALAPPDATA%\Programs`.

Hints for how to solve this:

* <https://stackoverflow.com/questions/33896015/per-user-install-always-requires-administrator-rights-if-dual-purpose-package-is>
* <https://github.com/wixtoolset/issues/issues/7137>
* <https://wixtoolset.org/docs/schema/wxs/packagescopetype/>
* <https://learn.microsoft.com/en-us/windows/win32/msi/single-package-authoring>

Maybe one must migrate from WiX v3 to v5?

* WiX Lifecycle: <https://wixtoolset.org/docs/about/#lifecycle>
  * v3 and v4 will be deprecated in February.
* v3 to v4: <https://wixtoolset.org/docs/fourthree/>
* v4 to v5: <https://wixtoolset.org/docs/fivefour/>
* <https://stackoverflow.com/questions/76338296/how-do-i-integrate-wixtool-set-with-github-actions>
* Example GitHub workflow: <https://github.com/CharaChorder/nexus/blob/master/.github/workflows/CI.yml>

Previously related issues and PRs:

* 2024-07-01: <https://github.com/nushell/nushell/issues/13281>
* 2024-08-26: <https://github.com/microsoft/winget-pkgs/issues/169379>
* 2024-08-26: <https://github.com/microsoft/winget-pkgs/pull/169381>

### How to reproduce

WinGet:

* `winget install --silent --id Nushell.Nushell`

Manually:

* Download MSI from latest [release v0.101.0](https://github.com/nushell/nushell/releases/tag/0.101.0)
* Start installer `nu-0.101.0-x86_64-pc-windows-msvc.msi` by double click => Prompts for admin.
* Start installer from CMD with `msiexec /i nu-0.101.0-x86_64-pc-windows-msvc.msi MSIINSTALLPERUSER=1 ALLUSERS=2` => Prompts for admin.

### Expected behavior

Should not require admin permissions when installing in user context.

### Configuration

Not relevant.

**Comment by fdncred** [comment]
I don't plan on changing this unless a perfect solution appears in a PR. Creating a winget-pkgs package has been a royal pain and I don't want to repeat it.

**Comment by o-l-a-v** [comment]
A part of the pain might be that the MSI wrongfully requires admin permissions to install for current user?

**Comment by fdncred** [comment]
You may be right, but I've chased so many issues with the winget-pkgs CI validator failing in so many weird ways that I'm not willing to change it unless someone proves to me that a change will pass it. If that happens, I don't have problems making the installer better but I'm not going to make those changes. I've been burned way too many times by winget-pkgs CI validator.

**Comment by o-l-a-v** [comment]
Here's a modified manifest that worked when testing locally. Just to show it's doable.

<details><summary>Nushell.Nushell.installer.yaml</summary>

```yaml
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.101.0
InstallerLocale: en-US
UpgradeBehavior: install
Commands:
  - nu
ReleaseDate: 2024-12-22
AppsAndFeaturesEntries:
Installers:
  - Architecture: arm64
    InstallerType: wix
    Scope: machine
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerUrl: https://github.com/nushell/nushell/releases/download/0.101.0/nu-0.101.0-aarch64-pc-windows-msvc.msi
    InstallerSha256: AC04BB9A99B35C1B8551A18D0F906F53728F3C197E2852F89D3B313FA2FE65AA
    ProductCode: '{F6E001EB-AE06-47D7-A3D6-8D2B2A8EA2C5}'
    AppsAndFeaturesEntries:
      - UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: nu.exe
        PortableCommandAlias: nu
    InstallerUrl: https://github.com/nushell/nushell/releases/download/0.101.0/nu-0.101.0-aarch64-pc-windows-msvc.zip
    InstallerSha256: 0E92CA38F53A22DB932252A6BCC820294B561EB85293E556E7909BAB040E3BBC
  - Architecture: x64
    InstallerType: wix
    Scope: machine
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerUrl: https://github.com/nushell/nushell/releases/download/0.101.0/nu-0.101.0-x86_64-pc-windows-msvc.msi
    InstallerSha256: C688ECFCCF7672F4632A35C0ADAD3A16FF53AC52E77CBD277A62F1973581E9F4
    ProductCode: '{86A71A75-017D-43E6-ADFB-3CFF1F008D32}'
    AppsAndFeaturesEntries:
      - UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: nu.exe
        PortableCommandAlias: nu
    InstallerUrl: https://github.com/nushell/nushell/releases/download/0.101.0/nu-0.101.0-x86_64-pc-windows-msvc.zip
    InstallerSha256: E2EB868D6FE97D4E2B43049F34047DF43774B3F7BE729CC7B84DDB0F0521B9AB
ManifestType: installer
ManifestVersion: 1.9.0

```

</details>

<details><summary>Nushell.Nushell.locale.en-US.yaml</summary>

```yaml
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.101.0
PackageLocale: en-US
Publisher: The Nushell Project Developers
PublisherUrl: https://www.nushell.sh
PublisherSupportUrl: https://github.com/nushell/nushell/issues
Author: The Nu Project Contributors
PackageName: nu
PackageUrl: https://github.com/nushell/nushell
License: MIT
LicenseUrl: https://github.com/nushell/nushell/blob/main/LICENSE
Copyright: Copyright (c) 2019 - 2021 Yehuda Katz, Jonathan Turner
CopyrightUrl: https://raw.githubusercontent.com/nushell/nushell/main/LICENSE
ShortDescription: A new type of shell
Description: |-
  Hello, and welcome to the Nushell project.
  The goal of this project is to take the Unix philosophy of shells, where pipes connect simple commands together, and bring it to the modern style of development.
  Nu takes cues from a lot of familiar territory, traditional shells like bash, object based shells like PowerShell, functional programming, systems programming, and more.
Moniker: nushell
Tags:
  - shell
  - rust
ReleaseNotesUrl: https://github.com/nushell/nushell/releases/tag/0.101.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0

```

</details>

<details><summary>Nushell.Nushell.yaml</summary>

```yaml
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.101.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0

```

</details>

PowerShell to test it

<details><summary>Test WinGet local packages</summary>

```pwsh
# Path
$ManifestDirPath = [System.IO.Path]::Combine(
    ([System.IO.Directory]::GetParent($psEditor.GetEditorContext().CurrentFile.Path).'FullName'),
    'Nushell v0.101.0'
)

# Try validating
winget validate --manifest $ManifestDirPath

# [admin] Enable required settings
gsudo {
    winget settings --enable LocalArchiveMalwareScanOverride
    winget settings --enable LocalManifestFiles
}

# Try installing
winget install --manifest $ManifestDirPath --installer-type portable --verbose

# Uninstall
winget uninstall --manifest $ManifestDirPath --purge

# [admin] Disable settings that was enabled
gsudo {
    winget settings --disable LocalArchiveMalwareScanOverride
    winget settings --disable LocalManifestFiles
}
```

</details>

Output from my testing:

```pwsh
PS > gsudo {
    winget settings --enable LocalArchiveMalwareScanOverride
    winget settings --enable LocalManifestFiles
}

PS >winget install --manifest $ManifestDirPath --installer-type portable --verbose
Found nu [Nushell.Nushell] Version 0.101.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/nushell/nushell/releases/download/0.101.0/nu-0.101.0-x86_64-pc-windows-msvc.zip
  ██████████████████████████████  33.6 MB / 33.6 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "nu"
Successfully installed

PS >winget uninstall --manifest $ManifestDirPath --purge
Found nu [Nushell.Nushell]
Starting package uninstall...
Purging install directory...
Successfully uninstalled

PS >gsudo {
    winget settings --disable LocalArchiveMalwareScanOverride
    winget settings --disable LocalManifestFiles
}
```

But you might want to wait for following improvements in WinGet:

* <https://github.com/microsoft/winget-cli/issues/2299>
* <https://github.com/microsoft/winget-cli/issues/4044>
