### ISSUE TITLE
Plugin should be compatible with nightly version

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#15083]
### Related problem

I have a plugin which have the following dependencies:
```toml
nu-plugin = { version = "0.102" }
nu-protocol = { version = "0.102", features= ["plugin"]}
```

But when I try to use it with nightly nushell, it raises the following error:
```
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Plugin `mongo` is compiled for nushell version 0.102.0, which is not compatible with version 0.102.1-nightly.6
```

### Describe the solution you'd like

Since nightly version is introduce by https://github.com/nushell/nushell/pull/14880
I think it's good to make nightly nushell version(e.g: 0.102.1-nightly.6) compatible with released version(e.g: 0.102.0)

### Additional context and details

Here is my plugin https://github.com/WindSoilder/nu_plugin_mongo
