### ISSUE TITLE
Are you interested in a labeler bot? (labels PRs automatically)

### ISSUE THREAD

**Issue by AucaCoyan** [nushell/nushell#15607]
### Question

Hey! sup? I found the other day biome js uses a labeler bot for the prs. Are you interested in it?

[Link to the labeler bot](https://github.com/actions/labeler)

### Additional context and details

Sample of use:
biome has a yaml like:
```yaml
# See https://github.com/actions/labeler

A-Cli:                                       # name of the tag 
- changed-files:
  - any-glob-to-any-file:
    - crates/biome_cli/**          # glob of files affected
    - crates/biome_fs/**
    - crates/biome_console/**

A-Core:
- changed-files:
  - any-glob-to-any-file:
    - crates/biome_deserializer/**
    - crates/biome_fs/**
    - crates/biome_rowan/**
# ... and so on
```

[source](https://github.com/biomejs/biome/blob/main/.github/labeler.yml)

and the specific workflow yaml:

```yaml
name: Label PRs

on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: depot-ubuntu-24.04-arm-small
    if: github.repository_owner == 'biomejs'
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
```

[source](https://github.com/biomejs/biome/blob/main/.github/workflows/labels.yml)
