### ISSUE TITLE
Custom Highlighting

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1701]
**Describe the solution you'd like**

Custom syntax highlighting done with a YAML config or something similar

Allow for custom highlighting sets
```yaml
built-in: yellow
external-command: green
# etc
```

**Describe alternatives you've considered**
Other data format such as TOML, JSON
