### ISSUE TITLE
chars in output that shouldn't be

### ISSUE THREAD

**Issue by jgtaylor** [nushell/nushell#1922]
**Describe the bug**
On Debian, trying to parse dpkg-query output with:
```
sudo dpkg-query -W -f='${Package}#${Version}\n' | lines | split-column -c "#" package version
```
produces output with the $ (dollar sign):
```
3689 │ $zip                                       │ $3.0-11+b1 
3690 │ $zlib1g                                    │ $1:1.2.11.dfsg-1 
3691 │ $zlib1g-dev                                │ $1:1.2.11.dfsg-1 
```
In bash/ksh, (without the lines, split-column, etc,) the output is as follows:
```
zip#3.0-11+b1
zlib1g#1:1.2.11.dfsg-1
zlib1g-dev#1:1.2.11.dfsg-1
```

**To Reproduce**
1.  run: `sudo dpkg-query -W -f='${Package}#${Version}\n' | lines | split-column -c "#" package version`

**Expected behavior**
Expected the output not to include formatting strings passed to `dpkg-query`

**Screenshots**
None

**Configuration (please complete the following information):**
 - OS: Debian buster (10.4)
 - Nu version (you can use the `version` command to find out): 0.14.0 
 - Optional features (if any): none (installed via `cargo install nu`

**Comment by jonathandturner** [comment]
@jgtaylor - before you do the `split column`, can you show what the output looks like? That could help us see what might be going wrong.

**Comment by jgtaylor** [comment]
`sudo dpkg-query -W -f='${Package}#${Version}\n' | lines`
produces:
... snipped ...
```
 3686 │ $zenity#$3.30.0-2 
 3687 │ $zenity-common#$3.30.0-2 
 3688 │ $zerofree#$1.1.1-1 
 3689 │ $zip#$3.0-11+b1 
 3690 │ $zlib1g#$1:1.2.11.dfsg-1 
 3691 │ $zlib1g-dev#$1:1.2.11.dfsg-1 
```
And without the `lines`:
```
$zenity-common#$3.30.0-2
$zerofree#$1.1.1-1
$zip#$3.0-11+b1
$zlib1g#$1:1.2.11.dfsg-1
$zlib1g-dev#$1:1.2.11.dfsg-1
```

**Comment by thegedge** [comment]
If I had to guess, this is similar to https://github.com/nushell/nushell/issues/1439. Fix one bug, introduce others 😭

**Comment by jgtaylor** [comment]
for what it's worth (though, it may be an entirely separate issue) - when one `| to json` or `| to yaml`, the `\n` is printed as well.

e.g.
```yaml
- package: $zenity-common
  version: "$3.30.0-2\n"
- package: $zerofree
  version: "$1.1.1-1\n"
- package: $zip
  version: "$3.0-11+b1\n"
- package: "$zlib1g:amd64"
  version: "$1:1.2.11.dfsg-1\n"
- package: "$zlib1g-dev:amd64"
  version: "$1:1.2.11.dfsg-1\n"
```
