### ISSUE TITLE
Rebinding key for accept autocomplete

### ISSUE THREAD

**Issue by medakk** [nushell/nushell#3028]
**Is your feature request related to a problem? Please describe.**
I can "accept" an autocomplete command with the [right arrow key](https://www.nushell.sh/cookbook/misc.html). Coming from fish, I prefer using Ctrl-F for this.

**Describe the solution you'd like**
A way to modify keybindings.yml to map Ctrl-F to "accept autocomplete"

**Describe alternatives you've considered**
I tried mapping Ctrl-F to forward one char:

```yml
- key:
    Ctrl: F
  binding:
    Move:
      ForwardChar: 1
```

This had no effect. 

**Additional context**
--

**Comment by fdncred** [comment]
I played with this a little bit but I'm guessing we might be confusing terms.
This will move the cursor right one character but only if the entire line is already written.
```yaml
- key:
    Ctrl: F
  binding:
    Move:
      ForwardChar: 1
```
You may be wanting to complete the hint.
This is what I have to complete a hint.
```yaml
# Complete Hint
- key:
    ShiftRight:
  binding:
    CompleteHint:
```
I haven't found a rustyline binding for complete-hint-word. It seems like it's all or nothing with rustyline.

**Comment by medakk** [comment]
Weird, Shift+Right does absolutely nothing for me. For example, this is my current shell prompt:

![image](https://user-images.githubusercontent.com/10536745/107255748-df592f00-69f5-11eb-88e8-71814bc3ec67.png)

Pressing Shift-Right does nothing. 

![image](https://user-images.githubusercontent.com/10536745/107255748-df592f00-69f5-11eb-88e8-71814bc3ec67.png)

Press Right completes the line:

![image](https://user-images.githubusercontent.com/10536745/107255817-f0a23b80-69f5-11eb-8326-3b74f793de25.png)

So my question is, how do I remap whatever functionality is offered by "Right" to Ctrl-F?

**Comment by fdncred** [comment]
Do you have this in your keybinding.yml?

```yaml
# Complete Hint
- key:
    ShiftRight:
  binding:
    CompleteHint:
```

**Comment by fdncred** [comment]
Also, you want to make sure `keybindings.yml` is located in the same folder as nushell's `config.toml`. For me, on windows it's `C:\Users\username\AppData\Roaming\nushell\nu\config`. You can find out what it is on your system by doing `echo $nu.keybinding-path` from within nushell.

**Comment by medakk** [comment]
Ahh, it works now. I wrongly assumed that the ShiftRight would take effect because it was in the "default keybindings" `docs/sample_config/keybindings.yml`.

Adding
```
- key:
    Ctrl: F
  binding:
    CompleteHint:
```
to keybindings.yml works.

Thank you!
