### ISSUE TITLE
0.28: alias not working

### ISSUE THREAD

**Issue by martinrode** [nushell/nushell#3188]
**Describe the bug**#
An alias reported by "config | get alias" is not working properly.

```
/Users/martin> config | get alias
───┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │                                                                      api6
───┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ /Users/martin/go/src/github.com/programmfabrik/apitest/apitest -c /Users/martin/go/src/github.com/programmfabrik/fylr/bin/fylr.yml --curl-bash
   │ --stop-on-fail
───┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

/Users/martin> /Users/martin/go/src/github.com/programmfabrik/apitest/apitest
The latest apitest tool, v 68
INFO[0000] No config "./apitest.yml" read (will only use command line parameters): open ./apitest.yml: no such file or directory
^C
/Users/martin> api6
error: Command not found
  ┌─ shell:9:1
  │
9 │ api6
  │ ^^^^ command not found
```

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
/Users/martin> version | pivot
───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                      Column1
───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.28.0
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.50.0
 3 │ cargo_version      │ cargo 1.50.0
 4 │ pkg_version        │ 0.28.0
 5 │ build_time         │ 2021-03-09 22:34:29
 6 │ build_rust_channel │ release
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

```
/Users/martin> cat "/Users/martin/Library/Application Support/org.nushell.nu/config.toml" | lines | last 2
───┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ [alias]
 1 │ api6 = "/Users/martin/go/src/github.com/programmfabrik/apitest/apitest -c /Users/martin/go/src/github.com/programmfabrik/fylr/bin/fylr.yml --curl-bash
   │ --stop-on-fail"
───┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by kubouch** [comment]
You put custom aliases/commands into the `startup` variable in config.toml: https://www.nushell.sh/book/aliases.html#persisting. Then, you can run `config | get startup` to see it.

It could look as follows:
```
startup = [
    "alias ll = ls -l",
    "def lc [p] { ls -a $p | get name }",
]
```
You should also be able to source a script  there, though I haven't tried myself.

**Comment by martinrode** [comment]
ok thx. that worked.

**Comment by jerzybrzoska** [comment]
The `startup` variable looks like this in my config.toml
```
startup = [
    "alias ana = echo "ana"",
    "alias la = ls --long",
    "alias yt = nice -19 pypy3 ~/youtube-dl/youtube_dl/__main__.py",
]
```
and forms the last lines of `config.toml`.
Aliases do not work. For example when I run `ana` I get:
>command ana not found

Does spacing matter in this configuration file or is it only for readability?

**Comment by kubouch** [comment]
@jerzybrzoska I think the problem might be that you put the `startup = [ ... ]` not in the root of the config but under another field. For example my Config.toml looks roughly like this:
```toml
nonzero_exit_errors = true
path = [
    "/home/kubouch/.cargo/bin",
    "/home/kubouch/.local/bin",
    "/usr/local/sbin",
    "/usr/local/bin",
    "/usr/bin",
]
prompt = "echo (starship prompt)"
startup = [
    "alias ll = ls -l",
    "alias la = ls -la",
    "def lc [p] { ls -a $p | get name }",
]
table_mode = "light"
use_starship = true

[env]
EDITOR = "vim"
PAGER = "less"
VISUAL = "vim"
TMP_DIR = "/tmp"

[line_editor]
edit_mode = "vi"
max_history_size = 1000
```

If I put `startup = [ ... ]` at the end of the file, it falls under `[line_editor]` and not at the config root. So the key is to keep it among the first entries.

Spacing doesn't matter, as far as I know, but I'm not a toml expert.
