### ISSUE TITLE
Reference environment variables in the config file

### ISSUE THREAD

**Issue by lunush** [nushell/nushell#3295]
**Is your feature request related to a problem? Please describe.**
Having many environment variables pointing to different folders with similar paths results in a lot of repetitive text and increases possibility of human error

**Describe the solution you'd like**
Support syntax like this:
```toml
[env]
CARGO_HOME = "$XDG_DATA_HOME/cargo"
```

**Describe alternatives you've considered**
Writing environment variables manually

**Additional context**
I am a Linux user and to keep my home directory clean, I set a bunch of environment variables. Many of them reference to each other which makes it easier to modify and understand them.

For example, this
```toml
[env]
# ...
GEM_HOME="/home/user/.local/share/gem"
GEM_PATH="/home/user/.local/share/gem"
GEM_BIN="/home/user/.local/share/gem/ruby/2.7.0/bin"
GEM_SPEC_CACHE="/home/user/.cache/gem"
BUNDLE_USER_CONFIG="/home/user/.config/gem/bundle"
BUNDLE_USER_CACHE="/home/user/.cache/gem/bundle"
BUNDLE_USER_PLUGIN="/home/user/.local/share/gem/bundle"
```
could be converted to something like this
```toml
[env]
# ...
GEM_HOME="$XDG_DATA_HOME/gem"
GEM_PATH="$XDG_DATA_HOME/gem"
GEM_BIN="$GEM_PATH/ruby/2.7.0/bin"
GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/gem/bundle"
BUNDLE_USER_CACHE="$XDG_CACHE_HOME/gem/bundle"
BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/gem/bundle"

```
---
For some reason, I thought that implementing this is as simple as parsing values after the config is read, but I just realized that it also has to be [converted back](https://github.com/nushell/nushell/blob/ac070ae942aaf8562058e5cc8ad287fb4bd2cb5b/crates/nu-data/src/config.rs#L304) if I understood correctly. Or maybe the variables could be parse when nu_data::config::env is called? I could try implementing this if it's not too difficult and other are ok with that.
