### ISSUE TITLE
Installation size using Homebrew is unacceptable (~350 MBs)

### ISSUE THREAD

**Issue by mhmdanas** [nushell/nushell#3896]
Well, not a bug with Nu per se, and not even sure if this should be reported here or on homebrew-core, so tell me if this should be opened there instead.

So I just run `brew upgrade` and was greeted with this:
```console
$ brew upgrade
...
==> Pouring nushell--0.35.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/nushell/0.35.0: 27 files, 343.2MB
...
```

(The size was also similar when I upgraded to 0.34.0, but I didn't notice at the time yet)

I'm not sure if this is known or not, but I thought I'd bring attention to this, as I don't think a shell should be taking up such a large chunk of disk space.

**Comment by fdncred** [comment]
We decided to prioritize build speed over build size. If you want to build with a smaller size add this to the root Cargo.toml.
```toml
[profile.release]
opt-level = 'z' #Optimize for size
lto = true #Link Time Optimization
codegen-units = 1 #Reduce parallel codegen units
```
If you're on linux you could strip the symbols too to make it smaller. Be warned, this could take a long time to build depending on your hardware.
