### ISSUE TITLE
Use dust instead of du

### ISSUE THREAD

**Issue by zim0369** [nushell/nushell#5476]
### Related problem

[dust](https://github.com/bootandy/dust) is better and faster than nushell's built-in `du`. It is also written in Rust.

### Describe the solution you'd like

Replace "du" with "dust"

**Comment by elferherrera** [comment]
You could write an alias for it

**Comment by zim0369** [comment]
> You could write an alias for it

yea, rn that's what I've done but would be nice as a default

**Comment by zim0369** [comment]
> What dependencies does it pull?

I'm not sure what you asked but maybe this from dust's `Cargo.toml`:
```toml
[dependencies]
ansi_term = "0.12"
clap = { version = "=3", features=["cargo"] }
lscolors = "0.7"
terminal_size = "0.1"
unicode-width = "0.1"
rayon="1"
thousands = "0.2"
stfu8 = "0.2"
regex = "1"
```
