### ISSUE TITLE
Cannot save a "table<name: string, version: string>" toml

### ISSUE THREAD

**Issue by melMass** [nushell/nushell#7510]
### Describe the bug

Cannot save a `table<name: string, version: string>` toml

It produces the following *invalid* toml:
```toml
[[]]
name = "numpy"
version = "1.23.4"

[[]]
name = "torchaudio"
version = "0.13.0"

[[]]
name = "soundfile"
version = "0.11.0"

[[]]
name = "urllib3"
version = "1.26.12"
  ```

### How to reproduce

```nu

# this doesn't work 
open requirements.txt | lines | parse "{name}~={version}" | save not_working.toml | open not_working.toml 

# this works 
open requirements.txt | lines | parse "{name}~={version}" | transpose -r | save working.toml | open working.toml
```

**sample file**
[requirements.txt](https://github.com/nushell/nushell/files/10250289/requirements.txt)

### Expected behavior

To either error out on save, or produce a valid `toml`

### Screenshots

![image](https://user-images.githubusercontent.com/7041726/208214070-0f7833df-847c-4f59-acd0-db1c395e04f1.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.1                                          |
| branch             | main                                            |
| commit_hash        | 1f9907d2ff7022eb846c4e01dabeb3a6eff2cff5        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.72.1                                          |
| build_time         | 2022-12-01 01:22:08 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | iselect, fileinfo                                            |

### Additional context

I'm migrating this from a Discord discussion as I don't have the time to look into updating nu right now, so this might be irrelevant for this reason.

**Comment by NotLebedev** [comment]
Nu cant produce correct toml for this situation because "Fixed" result:
```toml
[[qwe]]
name = "numpy"
version = "1.23.4"

[[qwe]]
name = "torchaudio"
version = "0.13.0"

[[qwe]]
name = "soundfile"
version = "0.11.0"

[[qwe]]
name = "urllib3"
version = "1.26.12"
```

would produce a record with table:

![image](https://user-images.githubusercontent.com/17511668/208244748-a93f45ad-dfb1-44f2-9dc7-ab489391b40a.png)

File nushell\crates\nu-command\src\formats\to\toml.rs on line 131:
```rust
Value::List { ref vals, span } => match &vals[..] {
    [Value::Record { .. }, _end @ ..] => helper(engine_state, v),
    _ => Err(ShellError::UnsupportedInput(
        "Expected a table with TOML-compatible structure from pipeline".to_string(),
        *span,
    )),
}
```
accepts a list on top level, which it should not?
