### ISSUE TITLE
`table --collapsed` does not show any colors

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8110]
### Related problem

i like `table --collapsed` but i see there is not color in the output...

i think that would be a great plus to have a similar coloring as `table` and `table --expand` :relieved: 

> **Note**
> in all the following, the images have been generated with the script at the bottom of this issue :wink: 

below is an example output of `table --collapsed` (_see script down below_)
![2](https://user-images.githubusercontent.com/44101798/219866670-a9841a25-05d5-4137-869b-dfe3b65a6bba.png)

### Describe the solution you'd like

i think i could be great to take inspiration from `table` and `table --expand`.
for instance, the same data as above (_see script down below_) but `--expand`ed gives

![1](https://user-images.githubusercontent.com/44101798/219866734-9346647e-3fca-4fee-8612-6f5658cf073b.png)

thus i think the following could be very great for `table --collapse` :yum: 
that is the same as the first image here but with similar colors as in the image just above, bringing the best of both worlds :relieved: 
![3](https://user-images.githubusercontent.com/44101798/219866742-906e041a-4b3d-4a11-bb60-6e72466bfd94.png)

## THE SCRIPT
- use this `TOML` file
```toml
# foo.toml

[package]
name = "benches"
version = "0.3.0"
authors = ["Nirvan Tyagi <nirvan.tyagi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
ark-ec = { version = "0.3", features = [ "parallel" ] }
ark-ff = { version = "0.3", features = [ "parallel" ] }
ark-poly = { version = "0.3", features = [ "parallel" ] }
ark-std = { version = "0.3", features = [ "parallel" ] }
ark-groth16 = { version = "0.3", features = [ "parallel", "r1cs" ] }
ark-crypto-primitives = { version = "0.3", features = [ "parallel", "r1cs" ] }
ark-bls12-381 = { version = "0.3", features = [ "curve" ] }
ark-ed-on-bls12-381 = "0.3"
ark-bls12-377 = { version = "0.3", features = [ "curve", "r1cs" ] }
ark-bw6-761 = "0.3"

ark-relations = "0.3"
ark-r1cs-std = "0.3"

digest = "0.9"
blake2 = "0.9"
csv = "1"

ark-inner-products = { path = "../inner_products" }
ark-ip-proofs = { path = "../ip_proofs" }
ark-dh-commitments = { path = "../dh_commitments" }

[[bench]]
name = "inner_products"
path = "benches/inner_products.rs"
harness = false

[[bench]]
name = "gipa"
path = "benches/gipa.rs"
harness = false

[[bench]]
name = "tipa"
path = "benches/tipa.rs"
harness = false

[[bench]]
name = "poly_commit"
path = "benches/poly_commit.rs"
harness = false

[[bench]]
name = "groth16_aggregation"
path = "benches/groth16_aggregation/bench.rs"
harness = false

[[example]]
name = "groth16_aggregation"
path = "examples/groth16_aggregation.rs"
```
- define a helper function
```bash
def highlight [thing: string] {
    str replace --all $thing $"(ansi green_bold)($thing)(ansi reset)"
}
```
- compute the original table and the colored collapsed version
```bash
let original = (
    open foo.toml | get dev-dependencies | transpose key value | take 3 | transpose -r | into record
)

mut res = ($original | table -c)

for name in (open foo.toml | get dev-dependencies | columns | append ["features" "path" "version"]) {
    $res = ($res | highlight $name)
}
```
- print all the things
```bash
print $"the original expanded: (ansi green)there are colors(ansi reset)"
$original | table -e
print ""
print $"the original collapsed: (ansi red)there are no colors...(ansi reset)"
$original | table -c
print ""
print $"my proposition: (ansi green)there are colors(ansi reset) :yum:"
$res
```
