### ISSUE TITLE
Crash when opening a CloudFormation task file

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#8278]
### Describe the bug

When trying to open a yaml file containing a CloudFormation task nushell panics instead of throwing an error.

Here's an example file that triggers this behavior:

```yaml
TaskRole:
    Type: AWS::IAM::Role
    Properties:
        RoleName: !Sub ${AWS::StackName}-task-role
        Path: /
        AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Principal:
                      Service:
                          - ecs-tasks.amazonaws.com
                  Action: sts:AssumeRole
        Policies:
            - PolicyName: !Sub ecs-${AWS::StackName}
              PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                      - Action:
                            - "ecs:RegisterTaskDefinition"
                            - "ecs:ListClusters"
                            - "ecs:DescribeContainerInstances"
                            - "ecs:ListTaskDefinitions"
                            - "ecs:DescribeTaskDefinition"
                            - "ecs:DeregisterTaskDefinition"
                            - "ecs:ListTagsForResource"
                        Effect: Allow
                        Resource: "*"
```

### How to reproduce

1. Save attached file as whatever.yaml
2. Open whatever.yaml in nushell

### Expected behavior

I expected nu not to crash. Failure to parse the file into a nushell data structure is expected since it contains CloudFormation specific expressions

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.76.0                                                                                      |
| branch             |                                                                                             |
| commit_hash        |                                                                                             |
| build_os           | linux-x86_64                                                                                |
| build_target       | x86_64-unknown-linux-gnu                                                                    |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)                                                         |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                             |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)                                                         |
| pkg_version        | 0.76.0                                                                                      |
| build_time         | 2023-02-22 17:47:51 +01:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | database, dataframe, default, trash, which, zip                                             |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

### Additional context

Does not crash when --raw flag is passed.
